### PR TITLE
fix: parsing scheme to better infer port instead of defaulting to 80

### PR DESCRIPTION
**Pull request by ArchangelX360**

### CODE REVIEW

**Comment by ArchangelX360** [comment]
I am not very accustom to Python module and imports so I would take any suggestion for testing this bit properly if required.

**Review by kdehairy — COMMENTED** [review]
To my knowledge, if the scheme is `https`, the method would be `CONNECT`. Hence, it won't end up in this `else` branch.

Can you please explain the problem you initially faced? May be my understanding is not correct, or the fix is somewhere else.

**Comment by ArchangelX360** [comment]
Axios NodeJS famous HTTP client is not issuing a CONNECT, hence falling in the specific case :/.

**Comment by kdehairy** [comment]
OK. There two ways to do an https request through a proxy. One, is to do a CONNECT request to an http proxy (like ours here) which means a normal http connection to the proxy with a tunneled https connection inside. 
Two: is to make an https connection to an https proxy (which we are not currently), and the proxy will make another https connection to the final distinction.

This patch is about making pac4cli act also as an https proxy (second way). To be able to do so and still preserve the secure nature of the requested connection, it needs to properly implement an https client (including validating server certificates and host ...etc).

I personally don't mind but the patch need to address this also. Otherwise the connection between pac4cli and the distention will be an insecure connection.

What do you think?

**Comment by ArchangelX360** [comment]
> OK. There two ways to do an https request through a proxy. One, is to do a CONNECT request to an http proxy (like ours here) which means a normal http connection to the proxy with a tunneled https connection inside.
> Two: is to make an https connection to an https proxy (which we are not currently), and the proxy will make another https connection to the final distinction.
> 
> This patch is about making pac4cli act also as an https proxy (second way). To be able to do so and still preserve the secure nature of the requested connection, it needs to properly implement an https client (including validating server certificates and host ...etc).
> 
> I personally don't mind but the patch need to address this also. Otherwise the connection between pac4cli and the distention will be an insecure connection.
> 
> What do you think?

Oh I see, I was lacking context on that. It seems like Axios is just doing a bad job with proxied request. I agree, we don't want this insecure connection.

I will close this merge request until we come with a better design to address the issue.

**Pull request closed without merging**
